- vllm_ascend_plugin/attention.py
[bugfix]: attention alibi bias shape is wrong.
> [bugfix]: attention alibi bias shape is wrong

- .gitignore
- README.md
- examples/offline_distributed_inference_npu.py
- examples/offline_inference_audio_language.py
- examples/offline_inference_npu.py
- vllm_ascend_plugin/attention.py
- vllm_ascend_plugin/platform.py
> [Docs] Update docs and code format

- README.md
- examples/offline_distributed_inference_npu.py
- examples/offline_inference_audio_language.py
- examples/offline_inference_npu.py
- format.sh
- requirements-lint.txt
- vllm_ascend_plugin/attention.py
- vllm_ascend_plugin/platform.py
[Format] Update docs and add `format.sh`.
> [Format] Update docs and add format.sh

- .github/mergify.yml
- .github/workflows/mypy.yaml
- .github/workflows/ruff.yml
- .github/workflows/shellcheck.yml
- .github/workflows/yapf.yml
- tools/mypy.sh
- vllm_ascend/communicator.py
- vllm_ascend/worker.py
Init CI for vllm-ascend.
Modified form https://github.com/vllm-project/vllm/tree/main/.github/workflows
This pr will focus on lint, and the remaining will be followed up in next pr. Plz let me know if I miss something.
> [CI] Init CI -- do lint

- vllm_ascend/platform.py
Add `device_control_env_var` for npu platform.
related pr: https://github.com/vllm-project/vllm/pull/12023
> Add device_control_env_var

- vllm_ascend/attention.py
- vllm_ascend/platform.py
* fix attention impl as https://github.com/vllm-project/vllm/pull/11690
* fix platform enum
> Tiny fixes

- CODE_OF_CONDUCT.md
Init CODE_OF_CONDUCT from https://github.com/vllm-project/vllm/blob/main/CODE_OF_CONDUCT.md .
Consider vLLM Ascend Plugin will be a vLLM umbrella project, so keep same with vLLM community.
> [Doc] Add CODE_OF_CONDUCT.md

- .github/workflows/actionlint.yml
- .github/workflows/mypy.yaml
- .github/workflows/ruff.yml
- .github/workflows/shellcheck.yml
- .github/workflows/yapf.yml
> [CI] enable CI for all branches

- vllm_ascend/__init__.py
- vllm_ascend/attention.py
- vllm_ascend/model_runner.py
- vllm_ascend/ops/__init__.py
- vllm_ascend/ops/activation.py
- vllm_ascend/ops/rotary_embedding.py
- vllm_ascend/worker.py
add two custom_ops: silu_and_mul and rope
replace three ops in attention layer: reshape_and_cache, pagedattention and flashattention
change the profile run strategy
> [Hardware][Ascend] Add silu_and_mul / rope ops and replace ops in attention layer

- vllm_ascend/__init__.py
… will cause circular import problem
> [Bugfix][Ascend] Remove the register of mindie_turbo from init of vllm_ascend

- .github/workflows/vllm_ascend_test.yaml
Use secret var instead of plaintext.
> [CI] use secret var

- setup.py
> [Doc] Add Apache 2.0 license header

- .github/workflows/vllm_ascend_test.yaml
Use cached vLLM to avoid CI failure due to network reason.
> [CI] use cached vLLM

- README.md
- docs/environment.md
This patch updates the readme doc for vLLM Ascend plugin.
> [Doc] Init vLLM Ascend plugin README.md

- .gitignore
Add Python ignore and `.DS_Store`
No
git status see related file ignored
> [Misc] Add Python ignore

- .github/workflows/vllm_ascend_test.yaml
- tools/npu-vllm-test.sh
> [CI][UT] init vLLM native UTs

- vllm_ascend/model_runner.py
- vllm_ascend/worker.py
* Refactor worker to decouple it from gpuworker
* add `get_model` func to `model_runner` and `worker`
plz merge this pr before #32 , because it relys on the reconstruction in this PR
> [worker] refactor worker to decouple it from gpuworker

- .github/workflows/vllm_ascend_test.yaml
- tests/test_offline_inference.py
- tools/npu-vllm-test.sh
Mainly changes: 
* exit if vLLM native ut failed
* rm redundant mappings in docker
* update TEST_FILES
`test_config.py` is disabled beacuse some models require for access:
> [CI] some fixes

- vllm_ascend/attention.py
Adapts AttentionLayer and kvcache scaling interface to make ci happy with master vLLM.
- https://github.com/vllm-project/vllm/commit/e97f802b2d74861af77997691a7d1c36498f6dca Add the dynamic kv cache scaling factors
- https://github.com/vllm-project/vllm/commit/86bfb6dba7c6e0650e7d7498cbd46b49155b2a42 Add AttentionLayer to forward
No
- run with master vllm
```
git clone --depth 1 https://github.com/vllm-project/vllm.git /workspace/vllm
python3 -m pip install -r /workspace/vllm/requirements-build.txt
VLLM_TARGET_DEVICE="empty" python3 -m pip install /workspace/vllm/
python3 -m pip install /workspace/vllm_ascend/
pytest tests -sv
```
- CI passed
> [Attention] Adapts AttentionLayer and kvcache scaling interface

- .github/workflows/vllm_ascend_test.yaml
- tools/npu-vllm-test.sh
Test with vllm master code to fix CI failure
No
By CI test
> [CI]Fix broken CI

- CONTRIBUTING.md
- Dockerfile
- README.md
- docs/environment.md
- Add `Building and testing` section to CONTRIBUTING.md
- Refresh Dockerfile to use empty VLLM_TARGET_DEVICE
No
Preview and test
> [Doc][Misc] Update README/CONTRIBUTING for better dev experience
